version: '3.8'

services:
  redis:
    image: 'bitnami/redis:latest'
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  mongo:
    image: mongo
    container_name: naologic-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
  app:
    entrypoint: ['nest', 'start', '--debug', '0.0.0.0:9229', '--watch']
    container_name: naologic-api
    build:
      context: .
    # command: npm run start:debug
    ports:
      - 3000:3000
      - 9229:9229
      - 8000:8000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - mongo
    env_file:
      - .env

volumes:
  db_data: {}
